const Content = () => {
  return (
  <section className="content">
    <article><p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor hic tempora aperiam cumque doloremque rerum tenetur quia ipsam quas blanditiis quisquam culpa tempore reiciendis in iure perspiciatis veniam, nam rem cum? Tempore, quibusdam excepturi aut natus et nulla magni! Sequi ut cum ipsum eveniet molestias officia recusandae totam modi iure?</p></article>
    <article><p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ad, dicta, itaque commodi distinctio eaque mollitia odit minus accusamus non quidem delectus. Asperiores atque, eum voluptate blanditiis at possimus expedita, distinctio aperiam quia laudantium architecto odit iste quod quaerat ducimus saepe esse quisquam eius perspiciatis ipsum? Nesciunt harum cumque expedita similique repudiandae alias animi maxime tempora. Expedita et ipsum accusantium fugit quidem similique aperiam debitis facere aut beatae amet aliquid illum numquam eius natus, ratione dolores! Voluptate alias quas sed odio aspernatur pariatur eos molestias explicabo consequatur atque. Impedit rerum aspernatur hic. Illum cum consequatur nulla harum in voluptatibus sint. Animi!</p></article>
    <article><p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor hic tempora aperiam cumque doloremque rerum tenetur quia ipsam quas blanditiis quisquam culpa tempore reiciendis in iure perspiciatis veniam, nam rem cum? Tempore, quibusdam excepturi aut natus et nulla magni! Sequi ut cum ipsum eveniet molestias officia recusandae totam modi iure?</p></article>
    <article><p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ad, dicta, itaque commodi distinctio eaque mollitia odit minus accusamus non quidem delectus. Asperiores atque, eum voluptate blanditiis at possimus expedita, distinctio aperiam quia laudantium architecto odit iste quod quaerat ducimus saepe esse quisquam eius perspiciatis ipsum? Nesciunt harum cumque expedita similique repudiandae alias animi maxime tempora. Expedita et ipsum accusantium fugit quidem similique aperiam debitis facere aut beatae amet aliquid illum numquam eius natus, ratione dolores! Voluptate alias quas sed odio aspernatur pariatur eos molestias explicabo consequatur atque. Impedit rerum aspernatur hic. Illum cum consequatur nulla harum in voluptatibus sint. Animi!</p></article>
    <article><p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor hic tempora aperiam cumque doloremque rerum tenetur quia ipsam quas blanditiis quisquam culpa tempore reiciendis in iure perspiciatis veniam, nam rem cum? Tempore, quibusdam excepturi aut natus et nulla magni! Sequi ut cum ipsum eveniet molestias officia recusandae totam modi iure?</p></article>
    <article><p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ad, dicta, itaque commodi distinctio eaque mollitia odit minus accusamus non quidem delectus. Asperiores atque, eum voluptate blanditiis at possimus expedita, distinctio aperiam quia laudantium architecto odit iste quod quaerat ducimus saepe esse quisquam eius perspiciatis ipsum? Nesciunt harum cumque expedita similique repudiandae alias animi maxime tempora. Expedita et ipsum accusantium fugit quidem similique aperiam debitis facere aut beatae amet aliquid illum numquam eius natus, ratione dolores! Voluptate alias quas sed odio aspernatur pariatur eos molestias explicabo consequatur atque. Impedit rerum aspernatur hic. Illum cum consequatur nulla harum in voluptatibus sint. Animi!</p></article>
  </section>
  )
};


export default Content;